### ISSUE TITLE
SSL connection not working after certificate flash on RP2040

### ISSUE THREAD

**Issue by alfonsoletizia1** [arduino/arduino-fwuploader#126]
Hi, 
I'm trying to flash the root CA certificate in order to connect to an FTP server with implicit SSL. 
Once i've flashed the .cer file the SSL features don't work anymore, not only I'm not able to connect to the FTPS server, but also, I cannot connect to some test SSL server, as arduino.cc:443, even if i try to upload the arduino certificate using the GUI tool in the IDE.

The only way I can restore the connect SSL functionality (to arduino.cc as a test, not the FTPS server) is to flash again the WifiNina firmware using the tool provided by the Arduino IDE. 

The root CA and the FTPS server certificates have been created locally using openssl. 

Need help about possibly errors I made flashing the .cer file. I tried also flashing the server certificate, in addition to the root CA.
The board I'm using is the Arduino RP2040 connect.

Thanks for the help.

**Comment by facchinm** [comment]
Hi @alfonsoletizia1 ,
this is a current limitation of the certificates handling on Nina modules, so when you run the `upload certificates` command all the previous ones are going to be erased.
To overcome this, please add all the certificates you are interested in in a single command, like
```
./arduino-fwuploader certificates flash --url arduino.cc:443,google.com:443 --file ~/Downloads/my_self_signed_.der  -b arduino:mbed_nano:nanorp2040connect -a /dev/ttyACM0
```

Hope it helps!

@umbynos can we add some documentation about this?
