### ISSUE TITLE
Temporary files are not cleaned up

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-fwuploader#158]
### Describe the problem

Arduino Firmware Uploader creates some temporary folders:

- Name format: `55770067919477794103602099745`
- Name: `fwuploader`

These persist even after the process completes.

The class of folder first on that list accumulates over time, which may eventually cause a performance impact.

### To reproduce

1. Take note of the contents of your temporary folder.
   - Windows:
     ```text
     C:\Users\<user name>\AppData\Local\Temp
     ```
   - Linux:
     ```text
     /tmp
     ```
   - macOS
     ```text
     $TMPDIR
     ```
1. Run the following command:
   ```text
   arduino-fwuploader firmware list
   ```
1. Examine the contents of your temporary folder.

🐛 An additional `55770067919477794103602099745` folder is present.
🐛 The `fwuploader` folder is still present.

### Expected behavior

Temporary files are cleaned up on exit.

### Arduino Language Server version

2b1ab093e0e4da146c4d73964fa104fd5b776449

### Operating system

- Windows
- Linux
- macOS

### Operating system version

- Windows 11
- Ubuntu 22.04
- macOS Ventura

### Additional context

Some operating systems may eventually do a clean-up on the temporary folder, but this is not guaranteed. It is better for the application to take care of clean up of any temporary files once they are no longer needed.

---

Additional reports:

- https://forum.arduino.cc/t/cleanup-of-tmp-seems-inop-kubuntu-20-04/1072075
- https://forum.arduino.cc/t/windows-10-ide-2-0-2-slow-start/1061136/4
- https://forum.arduino.cc/t/rc9-2-temporary-directories/1022812
- https://forum.arduino.cc/t/temporary-files-from-the-arduino-ide/1067309

---

Related:

- https://github.com/arduino/arduino-ide/issues/1779

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-fwuploader/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by gashtaan** [comment]
These folders named 55770067919477794* are still polluting the temp. This fix has not yet been released?
