### ISSUE TITLE
MKR Vidor 4000 NINA FW version

### ISSUE THREAD

**Issue by pcl04dl3tt3r** [arduino/arduino-fwuploader#160]
### Describe the problem

The list command only shows MKR Vidor 4000 NINA firmware up to version 1.1.0.  This comes from the global: ModuleFirmwareIndexGZURL = "https://downloads.arduino.cc/arduino-fwuploader/boards/module_firmware_index.json.gz"

However module_firmware_index.json in test data contains versions up to 1.4.5.

Is this an issue with the index file version hosted on arduino.cc or does the Vidor 4000 really not support any newer firmware?

### To reproduce

arduino-fwuploader.exe firmware list

scroll down to version listed for the MKR Vidor 4000

compare this to the contents of module_firmware_index.json

### Expected behavior

I'd like to be able to update the Vidor 4000 NINA firmware to a newer version.

### Arduino Firmware Uploader version

0e0fb39

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-fwuploader/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @pcl04dl3tt3r. This is actually intentional (see https://github.com/arduino/arduino-fwuploader/pull/98). Newer versions of the firmware are not compatible with the MKR Vidor 4000 so this is why they are not listed for that board.
