### ISSUE TITLE
Missing firmeware for MKR NB 1500

### ISSUE THREAD

**Issue by sladig** [arduino/arduino-fwuploader#27]
The newest firmware for the MKR NB 1500 isn't available via the updater. L05.11A02.16 or better the version SARA-R410M-02B-03-L0.0.00.00.05.12_A.02.19_IP (https://forum.arduino.cc/t/firmware-upgrade-for-ublox-sara-r410m-02b-on-the-mkr-nb-1500-2/699292/2) would be very helpful. 

The current process of updating the firmware is very complicated and underlines the very complicated usage of the MKR NB 1500 board.

**Comment by umbynos** [comment]
I'm sorry, but we decided to remove support for SARA module in #65
In any case the latest firmware cannot be uploded using serial, then  it's not possible to use this tool to update it..
