### ISSUE TITLE
NANO 33 IoT - Programmer not responding

### ISSUE THREAD

**Issue by seapike** [arduino/arduino-fwuploader#31]
### Current behavior

After uploading the WifiNINA FirmwareUpdater sketch to my Nano 33 IoT, when I then open the Firmware updater tool, select my board `Arduino NANO 33 IoT (dev/cu.usbmodem141401)` and attempt to Test connection, I get the error "Programmer not responding, Make sure that FirmwareUpdater sketch is loaded on the board"

### Expected behavior

Test connection responds with success

### Environment

- Updater version: 0.11.0
- OS and platform: MacOS, Arduino 1.8.13

### Additional context

I resolved this by modifying the sketch

```void setup() {
  Serial.begin(1000000);

  while (!ESP32BootROM.begin(921600)) {
    Serial.println("Unable to communicate with ESP32 boot ROM!");
    ESP32BootROM.end();
  }
}

**Comment by umbynos** [comment]
Closed for inactivity, Feel free to reopen it, if you think the problem is still present with the new version
