### ISSUE TITLE
I am completely lost 

### ISSUE THREAD

**Issue by billbee** [arduino/arduino-fwuploader#73]
### Environment

- Updater version: downloaded yesterday 
- OS and platform:mac catalina

**Comment by umbynos** [comment]
Hi @billbee. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you out over there:
https://forum.arduino.cc/
